version: "3.8"

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: skillsync-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: skillsync
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - skillsync-network

  # Redis Cache (for session storage and caching)
  redis:
    image: redis:7-alpine
    container_name: skillsync-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - skillsync-network

  # Backend Server
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: skillsync-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/skillsync?authSource=admin
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-jwt-key}
      - FRONTEND_URL=http://localhost:3000
      - GOOGLE_AI_API_KEY=${GOOGLE_AI_API_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - EMAIL_FROM=${EMAIL_FROM}
      - ENABLE_AI_FEATURES=true
      - ENABLE_EMAIL_NOTIFICATIONS=true
      - ENABLE_STRIPE_PAYMENTS=true
      - ENABLE_FILE_UPLOADS=true
    ports:
      - "5000:5000"
    volumes:
      - ./server/uploads:/app/uploads
      - ./server/logs:/app/logs
    depends_on:
      - mongodb
      - redis
    networks:
      - skillsync-network

  # Frontend Application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: skillsync-frontend
    restart: unless-stopped
    environment:
      - VITE_API_URL=http://localhost:5000
      - VITE_STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - VITE_ENABLE_AI_FEATURES=true
      - VITE_ENABLE_STRIPE_PAYMENTS=true
      - VITE_ENABLE_FILE_UPLOADS=true
      - VITE_APP_NAME=SkillSync
      - VITE_APP_VERSION=1.0.0
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - skillsync-network

  # Nginx Reverse Proxy (for production)
  nginx:
    image: nginx:alpine
    container_name: skillsync-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - frontend
      - backend
    networks:
      - skillsync-network
    profiles:
      - production

  # Development Frontend (Hot reload)
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: skillsync-frontend-dev
    restart: unless-stopped
    environment:
      - VITE_API_URL=http://localhost:5000
      - VITE_STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - VITE_ENABLE_AI_FEATURES=true
      - VITE_ENABLE_STRIPE_PAYMENTS=true
      - VITE_ENABLE_FILE_UPLOADS=true
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - skillsync-network
    profiles:
      - development

  # Development Backend (Hot reload)
  backend-dev:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: skillsync-backend-dev
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/skillsync?authSource=admin
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-jwt-key}
      - FRONTEND_URL=http://localhost:5173
      - GOOGLE_AI_API_KEY=${GOOGLE_AI_API_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - EMAIL_FROM=${EMAIL_FROM}
      - ENABLE_AI_FEATURES=true
      - ENABLE_EMAIL_NOTIFICATIONS=true
      - ENABLE_STRIPE_PAYMENTS=true
      - ENABLE_FILE_UPLOADS=true
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
      - ./server/uploads:/app/uploads
      - ./server/logs:/app/logs
    depends_on:
      - mongodb
      - redis
    networks:
      - skillsync-network
    profiles:
      - development

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  skillsync-network:
    driver: bridge
